
import Link from "next/link"
import Head from 'next/head'


interface HeaderProps{
    title: string;
}

const Header = (props: HeaderProps) => {

    return(
        <>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="sticky top-0 z-40 w-full backdrop-blur bg-gradient-to-r from-sky-500/50 to-fuchsia-700/50">
                <div className='flex min-w-full mb-2 font-sans text-white'>
                    <div className="max-w-8xl">
                        <div className="py-4 border-b border-slate-900/10 lg:px-8 lg:border-0 dark:border-slate-300/10 mx-4 lg:mx-0">
                            <div className="relative flex items-center">
                                <div className="mr-3 flex-none">
                                    <h1 className="font-semibold text-2xl">Welcome To My App</h1>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
            
        </>
        
    )
}

export default Header